### ISSUE TITLE
[EPIC] Pulp Doc Migration

### ISSUE THREAD

**Issue by pedro-psb** [pulp/pulpcore#5037]
This is a progress tracker for the **migration of Pulp repositories to the new docs standards** defined in [this document](https://hackmd.io/@pbrochad/SyfGeQc86). If something is missing or shouldn't be here, please leave a comment.

The criteria of done for each repository is:
- having a new `staging_docs` folder with the proposed [content-categories folder structure](https://hackmd.io/@pbrochad/SyfGeQc86#1-ContentGeneral-Repositories)
- having the markdown files from the old docs folder (either copied or converted from rst) in the appropriate categories/folders.

## Pulpcore

- [x] https://github.com/pulp/pulpcore/issues/5056

## Plugins

- [x] https://github.com/pulp/pulp_maven/issues/198
- [x] https://github.com/pulp/pulp_python/issues/646
- [x] https://github.com/pulp/pulp_gem/issues/227
- [x] https://github.com/pulp/pulp_ansible/issues/1754
- [x] https://github.com/pulp/pulpcore/issues/5054
- [x] https://github.com/pulp/pulp_container/issues/1517
- [x] https://github.com/pulp/pulp_deb/issues/1014
- [x] https://github.com/pulp/pulp_ostree/issues/347
- [x] https://github.com/pulp/pulp_rpm/issues/3445
- [x] https://github.com/pulp/pulpcore/issues/5055

## Extra

- [x] https://github.com/pulp/pulp-oci-images/issues/596
- [x] https://github.com/pulp/oci_env/issues/150
- [x] https://github.com/pulp/pulp-operator/issues/1212
- [x] https://github.com/pulp/pulp-cli/issues/903
- [x] https://github.com/pulp/pulp-openapi-generator/issues/94
- [x] https://github.com/pulp/pulpcore-selinux/issues/73
- [x] https://github.com/pulp/pulp-docs/issues/12

**Comment by lubosmj** [comment]
Documentation can be previewed locally by running `pulp-docs serve` (https://github.com/pedro-psb/pulp-docs). This should also tell you which URL the documentation is hosted on.
